### ISSUE TITLE
为什么interaction map可以解释为图像呢？

### ISSUE THREAD

**Issue by familyld** [duxy-me/ConvNCF#1]
图像的局部是有相似/相同的语义的，所以用CNN来提取特征是有意义的。但interaction map只是两个embedding的外积，对interaction map来说，有这样的局部意义吗？请问你是怎么思考这一点的呢？谢谢！

**Comment by duxy-me** [comment]
Our paper explained the efficacy of convolution. Actually, convolution is just a partial feature extractor, which doesn't require similar partial expressions in the known CNN applications. In images, the partial images and features on the border are different from those on the center. In NLP, the phrases at the beginning of the sentences are different from those at the ends. In other words, if there are sufficient convolutional filters, it will achieve the same expressiveness of fully-connected layers. Thus the keys using CNN in ConvNCF are 1) to ensure the final prediction contains all the interactions between the dimensions, and 2) to ensure there are adequate convolutional filters.

**Comment by familyld** [comment]
@duxy-me Impressive. Then there is still a lot to do.
