### ISSUE TITLE
ConvNCF.py still load the evaluate model...

### ISSUE THREAD

**Issue by boom85423** [duxy-me/ConvNCF#4]
I study recently your project at https://github.com/duxy-me/ConvNCF.
Our team think your idea is awesome.

There are something to trouble you...
Hope you could help me.
I found some bug in your code when I run ConvNCF.py
Console is still show the screeshot at attachment
I hope sincerly you can relp me.

Best regards.
Kevin Xu
![image](https://user-images.githubusercontent.com/38269155/45220553-1258df00-b2e1-11e8-8cec-21f47619d996.png)

**Comment by duxy-me** [comment]
I'm not sure about what your 'bug' means... Maybe the name 'evaluate model' is not accurate? In particular, it is a module for evaluating the current model parameters.

**Comment by duxy-me** [comment]
What is your environment? I notice that your verbose is 100. If you use tensorflow-CPU, you may need a long time to get the results.

**Comment by boom85423** [comment]
I use python3.6.4 to run the code.
I change some function like print "xxx" to print("xxx") to ensure it can run with python3.
Actually, it has run for long time then my laptop fan get very high temperature.

**Comment by duxy-me** [comment]
I think python 3.6 is all right. With i7 cpu, one epoch may cost hundreds
seconds. Since you set the verbose to 100, you may get the first output in
several hours. So the suggestion is, run the code with GPU or set the
verbose to 1.

**Comment by boom85423** [comment]
Thanks. It's work finally.
Have a nice day~
