### ISSUE TITLE
An Error "NameError: name 'dataset' is not defined" Occurred.

### ISSUE THREAD

**Issue by zhaohongbao** [duxy-me/ConvNCF#5]
Excuse me,when I attempt to run this paper's implements, some troubles caught me. Followed the "README.md", as I run  "python MF_BPR.py", an Error occurs. 

"NameError: name 'dataset' is not defined"

**Comment by s1162276945** [comment]
I have the same problem, I use Win OS, not Linux.

**Comment by zhaohongbao** [comment]
> I have the same problem, I use Win OS, not Linux.

At first, I run it in Win 7 OS, the above error occurred. finally, I found that it could run in Linux. Because the mechanism of multi-thread is different between Linux and Win OS. When I modified the source adapting to single-thread in Win7 OS, and it could run again.

**Comment by s1162276945** [comment]
> > I have the same problem, I use Win OS, not Linux.
> 
> At first, I run it in Win 7 OS, the above error occurred. finally, I found that it could run in Linux. Because the mechanism of multi-thread is different between Linux and Win OS. When I modified the source adapting to single-thread in Win7 OS, and it could run again.

ok, thank you.

**Comment by duxy-me** [comment]
> > I have the same problem, I use Win OS, not Linux.
> 
> At first, I run it in Win 7 OS, the above error occurred. finally, I found that it could run in Linux. Because the mechanism of multi-thread is different between Linux and Win OS. When I modified the source adapting to single-thread in Win7 OS, and it could run again.

Thanks for the kind comments! I didn't realize this problem is caused by the operating system. I thought this may be caused by another module with the same name `Dataset'.

**Comment by SinHaeFeng** [comment]
> > I have the same problem, I use Win OS, not Linux.
> 
> At first, I run it in Win 7 OS, the above error occurred. finally, I found that it could run in Linux. Because the mechanism of multi-thread is different between Linux and Win OS. When I modified the source adapting to single-thread in Win7 OS, and it could run again.
Could you tell me how to change muti-thread to single-thread in Win10 OS？

**Comment by SinHaeFeng** [comment]
I meet the same problem.Could you tell me how to change the source adapting to single-thread?
