### ISSUE TITLE
运行 python MF_BPR.py 

### ISSUE THREAD

**Issue by s1162276945** [duxy-me/ConvNCF#6]
Epoch 0 [2.2s + 10.6s]: HR = 0.1706, NDCG = 0.0905 AUC = 0.7705 train_AUC = 0.0000 [46.4s] ACC = 0.5003 train_loss = 0.0000 ACC = 0.0000 [0.0s]
Epoch 50 [2.4s + 10.2s]: HR = 0.2545, NDCG = 0.1337 AUC = 0.9258 train_AUC = 0.0000 [32.8s] ACC = 0.9674 train_loss = 0.0000 ACC = 0.0000 [0.0s]
Epoch 100 [2.4s + 10.1s]: HR = 0.2651, NDCG = 0.1379 AUC = 0.9295 train_AUC = 0.0000 [41.5s] ACC = 0.9730 train_loss = 0.0000 ACC = 0.0000 [0.0s]
Epoch 150 [2.4s + 9.8s]: HR = 0.2695, NDCG = 0.1390 AUC = 0.9305 train_AUC = 0.0000 [41.5s] ACC = 0.9759 train_loss = 0.0000 ACC = 0.0000 [0.0s]
Epoch 200 [2.4s + 9.9s]: HR = 0.2795, NDCG = 0.1474 AUC = 0.9318 train_AUC = 0.0000 [42.0s] ACC = 0.9777 train_loss = 0.0000 ACC = 0.0000 [0.0s]
Epoch 250 [1.6s + 3.5s]: HR = 0.2801, NDCG = 0.1464 AUC = 0.9323 train_AUC = 0.0000 [18.6s] ACC = 0.9792 train_loss = 0.0000 ACC = 0.0000 [0.0s]
Epoch 300 [1.7s + 3.5s]: HR = 0.2822, NDCG = 0.1485 AUC = 0.9330 train_AUC = 0.0000 [17.8s] ACC = 0.9798 train_loss = 0.0000 ACC = 0.0000 [0.0s]
Epoch 350 [1.6s + 3.5s]: HR = 0.2875, NDCG = 0.1516 AUC = 0.9334 train_AUC = 0.0000 [18.3s] ACC = 0.9806 train_loss = 0.0000 ACC = 0.0000 [0.0s]
Epoch 400 [1.7s + 3.5s]: HR = 0.2840, NDCG = 0.1491 AUC = 0.9336 train_AUC = 0.0000 [18.6s] ACC = 0.9807 train_loss = 0.0000 ACC = 0.0000 [0.0s]
Epoch 450 [1.6s + 3.5s]: HR = 0.2841, NDCG = 0.1490 AUC = 0.9335 train_AUC = 0.0000 [17.7s] ACC = 0.9815 train_loss = 0.0000 ACC = 0.0000 [0.0s]
Epoch 499 [1.6s + 3.5s]: HR = 0.2860, NDCG = 0.1490 AUC = 0.9337 train_AUC = 0.0000 [18.4s] ACC = 0.9820 train_loss = 0.0000 ACC = 0.0000 [0.0s]
best:Epoch 350 [1.6s + 3.5s]: HR = 0.2875, NDCG = 0.1516 AUC = 0.9334 train_AUC = 0.0000 [18.3s] ACC = 0.9806 train_loss = 0.0000 ACC = 0.0000 [0.0s]

**Comment by s1162276945** [comment]
What is the research motivation of outer product? Are there any related papers?

**Comment by EdisonLeeeee** [comment]
> 
> 
> What is the research motivation of outer product? Are there any related papers?

Common matrix factorization(MF) — the dominant method for CF — which considers only diagonal elements in the interaction map(outer-product matrix), while ConvNCF encodes more signal than MF by accounting for the correlations between different embedding dimensions.
Related paper: *Outer Product-based Neural Collaborative Filtering*
[Uploading Outer Product-based Neural Collaborative Filtering.pdf…]()

**Comment by duxy-me** [comment]
> > What is the research motivation of outer product? Are there any related papers?
> 
> Common matrix factorization(MF) — the dominant method for CF — which considers only diagonal elements in the interaction map(outer-product matrix), while ConvNCF encodes more signal than MF by accounting for the correlations between different embedding dimensions.
> Related paper: _Outer Product-based Neural Collaborative Filtering_
> Uploading Outer Product-based Neural Collaborative Filtering.pdf…



> > What is the research motivation of outer product? Are there any related papers?
> 
> Common matrix factorization(MF) — the dominant method for CF — which considers only diagonal elements in the interaction map(outer-product matrix), while ConvNCF encodes more signal than MF by accounting for the correlations between different embedding dimensions.
> Related paper: _Outer Product-based Neural Collaborative Filtering_
> Uploading Outer Product-based Neural Collaborative Filtering.pdf…

Thank @EdisonLeeeee .
