### ISSUE TITLE
The evaluate function is Pretty Confusing

### ISSUE THREAD

**Issue by hongxin001** [duxy-me/ConvNCF#7]
https://github.com/duxy-me/ConvNCF/blob/14674bc94ed3e071747b55ca71d7717390a23110/ConvNCF.py#L494

I don't know why there are two return statement in the function, and the first function return the result of K=5,10,20 ? 

I can't help wanting to diss the code~ maybe you can check more carefully before publish.

**Comment by duxy-me** [comment]
Thank you for pointing that out. Your dissing would help the codes better.
