### ISSUE TITLE
An Error "NameError: name 'dataset' is not defined" Occurred.

### ISSUE THREAD

**Issue by SinHaeFeng** [duxy-me/ConvNCF#8]
我的环境是win10+anconda3+tensorflow1.8，但是在跑代码时出现了这个错误，请问您知道该怎么解决吗？谢谢

**Comment by duxy-me** [comment]
The issue was discussed in #5 . Since I do not have the win10 execution environment, I can't obtain the error. Maybe you could follow the suggestion given by zhaohongbao in #5, and remove the implementations with `multiprocessing' package.

**Comment by SinHaeFeng** [comment]
OK，thank you.I will have a try.
